#!/usr/bin/python3

import argparse

from git import Repo

from gitlab_clone_all_utils import RepoProcessor


class Worker(RepoProcessor):
    def _process(self, repo: Repo, path: str) -> None:
        cfg = repo.config_writer()
        if not cfg.has_section('user'):
            cfg.add_section('user')
        cfg.set('user', 'name', self._args.author)
        if self._args.email:
            cfg.set('user', 'email', self._args.email)
        cfg.write()
        print('{}: {} <{}>'.format(path,
                                   cfg.get('user', 'name'),
                                   cfg.get('user', 'email') or 'no email'))


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Set author and email for all repos '
                                                 'found under the current directory')
    parser.add_argument('author', help='Author name')
    parser.add_argument('email', nargs='?', default='', help='Author email')
    Worker.execute(parser)
