#!/usr/bin/python3

import argparse
import sys

from gitlab_clone_all_utils import TipHandler, RepoProcessor


class Worker(RepoProcessor, TipHandler):
    def _process(self, repo, path):
        print('Processing {}:'.format(path))
        commits = self._commits_per_head(repo.heads)
        for head in commits:
            if head.name in self._args.exclude:
                continue
            if head.commit == repo.head.commit:
                continue
            if not self._args.include_tracking and head.tracking_branch():
                continue
            if not self._is_tip(head, commits):
                print('{} is not a tip.'.format(head.name))
                do_remove = True
                if not self._args.auto:
                    answer = input('Remove? [yes]/no/quit: ')
                    if answer.lower() in ['q', 'quit']:
                        sys.exit(0)
                    do_remove = not answer or answer.lower() in ['y', 'yes']
                if do_remove:
                    repo.delete_head(head)
                    print('Removed.')
        print('Processed {}\n'.format(path))


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Delete local branches that are not tips')
    parser.add_argument('-x', '--exclude', type=str, nargs='+', default=[],
                        help='Exclude these branches')
    parser.add_argument('-t', '--include-tracking', action='store_true',
                        help='Include tracking branches')
    parser.add_argument('-a', '--auto', action='store_true',
                        help='Automatically remove branches instead of asking each time')
    Worker.execute(parser)
